# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pl.ui'
#
# Created: Wed Nov 23 21:58:26 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1208, 919)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 1161, 521))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(23)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.LifterNameLabel = QtGui.QLabel(self.centralwidget)
        self.LifterNameLabel.setGeometry(QtCore.QRect(20, 10, 431, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LifterNameLabel.setFont(font)
        self.LifterNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LifterNameLabel.setScaledContents(False)
        self.LifterNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LifterNameLabel.setObjectName(_fromUtf8("LifterNameLabel"))
        self.LiftSelected = QtGui.QComboBox(self.centralwidget)
        self.LiftSelected.setGeometry(QtCore.QRect(10, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LiftSelected.setFont(font)
        self.LiftSelected.setObjectName(_fromUtf8("LiftSelected"))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.LiftSelected.addItem(_fromUtf8(""))
        self.RackLabel = QtGui.QLabel(self.centralwidget)
        self.RackLabel.setGeometry(QtCore.QRect(10, 220, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RackLabel.setFont(font)
        self.RackLabel.setObjectName(_fromUtf8("RackLabel"))
        self.Weight_kg = QtGui.QLabel(self.centralwidget)
        self.Weight_kg.setGeometry(QtCore.QRect(310, 100, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.Weight_kg.setFont(font)
        self.Weight_kg.setObjectName(_fromUtf8("Weight_kg"))
        self.Weight_lb = QtGui.QLabel(self.centralwidget)
        self.Weight_lb.setGeometry(QtCore.QRect(310, 160, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.Weight_lb.setFont(font)
        self.Weight_lb.setObjectName(_fromUtf8("Weight_lb"))
        self.LoadDataButton = QtGui.QPushButton(self.centralwidget)
        self.LoadDataButton.setGeometry(QtCore.QRect(190, 190, 98, 27))
        self.LoadDataButton.setObjectName(_fromUtf8("LoadDataButton"))
        self.GoodButton = QtGui.QPushButton(self.centralwidget)
        self.GoodButton.setGeometry(QtCore.QRect(190, 110, 98, 27))
        self.GoodButton.setStyleSheet(_fromUtf8("background-color: rgb(68, 255, 0);"))
        self.GoodButton.setObjectName(_fromUtf8("GoodButton"))
        self.BadButton = QtGui.QPushButton(self.centralwidget)
        self.BadButton.setGeometry(QtCore.QRect(190, 150, 98, 27))
        self.BadButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 4);"))
        self.BadButton.setObjectName(_fromUtf8("BadButton"))
        self.FlightSelected = QtGui.QComboBox(self.centralwidget)
        self.FlightSelected.setGeometry(QtCore.QRect(10, 170, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FlightSelected.setFont(font)
        self.FlightSelected.setObjectName(_fromUtf8("FlightSelected"))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.FlightSelected.addItem(_fromUtf8(""))
        self.kg25 = QtGui.QLabel(self.centralwidget)
        self.kg25.setGeometry(QtCore.QRect(480, 50, 66, 17))
        self.kg25.setObjectName(_fromUtf8("kg25"))
        self.kg20 = QtGui.QLabel(self.centralwidget)
        self.kg20.setGeometry(QtCore.QRect(480, 80, 66, 17))
        self.kg20.setObjectName(_fromUtf8("kg20"))
        self.kg15 = QtGui.QLabel(self.centralwidget)
        self.kg15.setGeometry(QtCore.QRect(480, 110, 66, 17))
        self.kg15.setObjectName(_fromUtf8("kg15"))
        self.kg10 = QtGui.QLabel(self.centralwidget)
        self.kg10.setGeometry(QtCore.QRect(480, 140, 66, 17))
        self.kg10.setObjectName(_fromUtf8("kg10"))
        self.kg5 = QtGui.QLabel(self.centralwidget)
        self.kg5.setGeometry(QtCore.QRect(480, 160, 66, 17))
        self.kg5.setObjectName(_fromUtf8("kg5"))
        self.kg2 = QtGui.QLabel(self.centralwidget)
        self.kg2.setGeometry(QtCore.QRect(480, 180, 66, 17))
        self.kg2.setObjectName(_fromUtf8("kg2"))
        self.kg1 = QtGui.QLabel(self.centralwidget)
        self.kg1.setGeometry(QtCore.QRect(480, 200, 66, 17))
        self.kg1.setObjectName(_fromUtf8("kg1"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuLoad = QtGui.QMenu(self.menubar)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuLoad.addSeparator()
        self.menuLoad.addAction(self.actionSave)
        self.menuLoad.addAction(self.actionLoad)
        self.menubar.addAction(self.menuLoad.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Flt", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Team", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Div", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bwt", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "WtCls", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Lot#", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sq Rack", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "SQ-1", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "SQ-2", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "SQ-3", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Best Sq", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "BP Rack", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "BP-1", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "BP-2", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "BP-3", None))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Best BP", None))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Sub-total", None))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "DL-1", None))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "DL-2", None))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "DL-3", None))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Best DL", None))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Total", None))
        self.LifterNameLabel.setText(_translate("MainWindow", "Lifter Name", None))
        self.LiftSelected.setItemText(0, _translate("MainWindow", "Squat 1", None))
        self.LiftSelected.setItemText(1, _translate("MainWindow", "Squat 2", None))
        self.LiftSelected.setItemText(2, _translate("MainWindow", "Squat 3", None))
        self.LiftSelected.setItemText(3, _translate("MainWindow", "Bench 1", None))
        self.LiftSelected.setItemText(4, _translate("MainWindow", "Bench 2", None))
        self.LiftSelected.setItemText(5, _translate("MainWindow", "Bench 3", None))
        self.LiftSelected.setItemText(6, _translate("MainWindow", "Deadlift 1", None))
        self.LiftSelected.setItemText(7, _translate("MainWindow", "Deadlift 2", None))
        self.LiftSelected.setItemText(8, _translate("MainWindow", "Deadlift 3", None))
        self.RackLabel.setText(_translate("MainWindow", "Rack 10", None))
        self.Weight_kg.setText(_translate("MainWindow", "100 Kg", None))
        self.Weight_lb.setText(_translate("MainWindow", "220 Lb", None))
        self.LoadDataButton.setText(_translate("MainWindow", "Load Data", None))
        self.GoodButton.setText(_translate("MainWindow", "Good Lift", None))
        self.BadButton.setText(_translate("MainWindow", "Bad Lift", None))
        self.FlightSelected.setItemText(0, _translate("MainWindow", "A", None))
        self.FlightSelected.setItemText(1, _translate("MainWindow", "B", None))
        self.FlightSelected.setItemText(2, _translate("MainWindow", "C", None))
        self.FlightSelected.setItemText(3, _translate("MainWindow", "D", None))
        self.FlightSelected.setItemText(4, _translate("MainWindow", "E", None))
        self.FlightSelected.setItemText(5, _translate("MainWindow", "F", None))
        self.FlightSelected.setItemText(6, _translate("MainWindow", "G", None))
        self.FlightSelected.setItemText(7, _translate("MainWindow", "H", None))
        self.FlightSelected.setItemText(8, _translate("MainWindow", "I", None))
        self.FlightSelected.setItemText(9, _translate("MainWindow", "J", None))
        self.FlightSelected.setItemText(10, _translate("MainWindow", "K", None))
        self.FlightSelected.setItemText(11, _translate("MainWindow", "L", None))
        self.kg25.setText(_translate("MainWindow", "TextLabel", None))
        self.kg20.setText(_translate("MainWindow", "TextLabel", None))
        self.kg15.setText(_translate("MainWindow", "TextLabel", None))
        self.kg10.setText(_translate("MainWindow", "TextLabel", None))
        self.kg5.setText(_translate("MainWindow", "TextLabel", None))
        self.kg2.setText(_translate("MainWindow", "TextLabel", None))
        self.kg1.setText(_translate("MainWindow", "TextLabel", None))
        self.menuLoad.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))

